application: leonardoluartenet
version: 3
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /css
  static_dir: web/stylesheets
- url: /img/
  static_dir: web/images
- url: /js/
  static_dir: web/scripts
- url: /static/
  static_dir: static/
- url: /scripts/(\D*?)
  script: modules/maintainance/\1.py
- url: /(\D*?)/.*  
  script: modules/\1/\1.py
- url: /.*
  script: modules/default/index.py
